version: '3'
services:
  app:
    image: fanticheli/lanchonete-creusa-clean-arch
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge